package com.wecompli.utils.sheardpreference

object PreferenceConstent {
    // var selecttab: String="selecttab"
    var Show_fragment_servicing = "Show_fragment_servicing"
    var iS_LOGIN = "islogin"
    var username_key = "loginusername"
    var password_key = "password"
    var iS_Checked_login = "checklogin"
    var loginuser_data = "userdata"
    var loginuser_name = "username"
    var loginuser_id = "userid"
    var loginuser_token="token"
    var site_id = "siteid"
    var park_id = "parkid"
    var search_date = "search_date"
    var periodic_session_ids = "periodic_session_ids"
    var check_mode = "checkmodetype"
    var component_mode = "componentmode"
    var signdraw = false
    var notifyemail = "notifyemaul"
    var e_id = "eleid"
    var assi_id = "assignid"
    var check_date = "check_date1"
    var checked_list_date = "check_list_date"
    var element_id = "element_id"
    var assign_id = "assign_id"
    var total_fault = "total_fault"
    var selected_company_name = "seleclted_company_nmae"
    var selected_site_name = "selected_site_name"

    var selected_company_id = "selected_company_id"
    var selected_site_id = "selected_site_id"
    var selected_bcom_name = "selected_bcom_name"
    var selected_bcom_element_name = "selected_bcom_element_name"
    var selected_faulttype = "Fault_Type"
    var selected_bcom_element_id = "selected_bcom_element_id"
    var selected_bcom_element_name_description = "selected_bcom_element_bescription"
    var fault_choose = "choose"

    var selecttab = "tab"
    var logingroupid = "groupid"
    var showintropage = "intropage"
    var selectfragment = "selectedfragment"
    var frarmentaudit = "audit"
    var frarmentstartcheck = "startcheck"
    var frarmentdashboard = "dashboard"
    var isdeleteposition = "isdeleteposition"
    var deleteposition = "deleteposition"
    var selectedlanagage = "selectedlanagage"

    var category_purpose="checks"
    var process_status="Y"
    var Selected_Sesson_id=""
    var Selectedcompany_id=""
    var faultid="fid"
    var notifyemil_list="nemil"
    var SelectedEmail="selectedemail"
    var UserCompany="company"
    var UserSite="site"
    var Category_name="category_name"
    var CheckName="check_name"
    var SelectedFaultId="fid"

    var component_totalfault="compnenttotal"
    var date_totalfault="datetotalfault"
    var siteidtotalfault="siteidtotalfauly"
    var companyidtotalfault="companyidtotalfault"
    var failselection="fail"
    var sessionname="sessionname"
    //var faultid=""
  //  var selecttab="selecttab"

}
